import React, { Component, useEffect, useState } from 'react';
import { AlertTriangle, BarChart3, Bell, CalendarClock, CheckCircle2, ClipboardList, Clock3, Dog, FileWarning, History, LogOut, Menu, PawPrint, Pencil, Search, ShieldCheck, Star, Trash2, UserRound, Users, X } from 'lucide-react';
import { api, session } from './api.js';

const roleNav = {
  admin: [{ id: 'dashboard', label: 'Resumen', icon: BarChart3, group:'Principal' }, { id: 'users', label: 'Usuarios', icon: Users, group:'Gestión' }, { id: 'reports', label: 'Denuncias', icon: FileWarning, group:'Gestión' }, { id: 'reviews', label: 'Reseñas', icon: Star, group:'Gestión' }, { id: 'audit', label: 'Auditoría', icon: ClipboardList, group:'Control' }],
  user: [{id:'summary',label:'Mi resumen',icon:BarChart3,group:'Principal'},{id:'active',label:'Reservas activas',icon:Clock3,group:'Servicios'},{id:'upcoming',label:'Próximas reservas',icon:CalendarClock,group:'Servicios'},{id:'history',label:'Historial',icon:History,group:'Servicios'},{id:'myreports',label:'Mis denuncias',icon:FileWarning,group:'Soporte'},{id:'notifications',label:'Notificaciones',icon:Bell,group:'Soporte'},{id:'profile',label:'Mi perfil',icon:UserRound,group:'Mi cuenta'},{id:'pets',label:'Mis mascotas',icon:PawPrint,group:'Mi cuenta'}],
  walker: [{id:'summary',label:'Mi resumen',icon:BarChart3,group:'Principal'},{id:'profile',label:'Mi perfil',icon:UserRound,group:'Mi cuenta'},{id:'verification',label:'Verificación',icon:ShieldCheck,group:'Mi cuenta'},{id:'availability',label:'Disponibilidad',icon:CalendarClock,group:'Mi cuenta'},{id:'active',label:'Servicios activos',icon:Clock3,group:'Servicios'},{id:'upcoming',label:'Próximos servicios',icon:Dog,group:'Servicios'},{id:'history',label:'Historial',icon:History,group:'Servicios'},{id:'reviews',label:'Calificaciones',icon:Star,group:'Actividad'},{id:'myreports',label:'Denuncias',icon:FileWarning,group:'Actividad'},{id:'notifications',label:'Notificaciones',icon:Bell,group:'Actividad'}],
};
const labels = { user: 'Dueño', walker: 'Paseador', active: 'Activo', warned: 'Advertido', suspended: 'Suspendido', blocked: 'Bloqueado', pending: 'Pendiente', reviewed: 'En revisión', dismissed: 'Desestimada', action_taken: 'Acción aplicada', low: 'Baja', medium: 'Media', high: 'Alta', critical: 'Crítica' };
const fmt = (date) => {
  const parsed = date ? new Date(date) : null;
  return parsed && !Number.isNaN(parsed.getTime())
    ? new Intl.DateTimeFormat('es-PA', { dateStyle: 'medium', timeStyle: 'short' }).format(parsed)
    : '—';
};

class ErrorBoundary extends Component {
  constructor(props) { super(props); this.state = { error: null }; }
  static getDerivedStateFromError(error) { return { error }; }
  componentDidCatch(error) { console.error('Error de interfaz:', error); }
  componentDidUpdate(previousProps) {
    if (previousProps.screen !== this.props.screen && this.state.error) this.setState({ error: null });
  }
  render() {
    if (!this.state.error) return this.props.children;
    return <section className="state-card error-state"><AlertTriangle/><h2>No pudimos mostrar esta sección</h2><p>{this.state.error.message || 'Ocurrió un error inesperado.'}</p><button onClick={() => this.setState({ error: null })}>Intentar nuevamente</button></section>;
  }
}

function PageState({ loading, error, empty, onRetry }) {
  if (loading) return <section className="state-card"><div className="spinner"/><h3>Cargando información…</h3></section>;
  if (error) return <section className="state-card error-state"><AlertTriangle/><h3>No se pudo cargar la información</h3><p>{error}</p><button onClick={onRetry}>Reintentar</button></section>;
  if (empty) return <section className="state-card"><ClipboardList/><h3>Todavía no hay registros</h3><p>Los datos aparecerán aquí cuando estén disponibles.</p></section>;
  return null;
}

function Login({ onLogin }) {
  const [form, setForm] = useState({ email: '', password: '' }), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const submit = async (e) => { e.preventDefault(); setBusy(true); setError(''); try { const data = await api('/api/admin/auth/login', { method: 'POST', body: JSON.stringify(form) }); session.set(data.token); onLogin(data.user); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <main className="login"><section className="login-brand"><img className="login-logo" src="/walkwi-logo.png" alt="Walkwi"/><p>PORTAL WALKWI</p><h1>Bienestar, confianza y cuidado en cada paseo.</h1><span>Walkwi conecta familias y paseadores para crear experiencias seguras, cercanas y felices para cada mascota.</span></section><section className="login-panel"><form onSubmit={submit}><img className="form-logo" src="/walkwi-logo.png" alt="Walkwi"/><PawPrint size={34}/><h2>Accede a tu cuenta</h2><p>Portal para dueños, paseadores y equipo administrativo.</p><label>Correo<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required autoFocus/></label><label>Contraseña<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></label>{error&&<div className="error">{error}</div>}<button disabled={busy}>{busy?'Verificando…':'Ingresar a Walkwi'}</button><div className="register-message"><span>¿Todavía no tienes una cuenta?</span><strong>Regístrate desde la aplicación móvil de Walkwi.</strong></div></form></section></main>;
}

function Dashboard() {
  const [data,setData]=useState(null),[error,setError]=useState('');
  const load=()=>{setError('');api('/api/admin/dashboard').then(setData).catch(e=>setError(e.message))}; useEffect(load,[]);
  const cards = data ? [{k:'owners',l:'Dueños',i:Users},{k:'walkers',l:'Paseadores',i:Dog},{k:'verifiedWalkers',l:'Verificados',i:ShieldCheck},{k:'pendingVerification',l:'Por verificar',i:Clock3},{k:'pendingReports',l:'Denuncias pendientes',i:FileWarning},{k:'criticalReports',l:'Denuncias críticas',i:AlertTriangle}] : [];
  return <><Header title="Centro de operaciones" subtitle="Estado general de la comunidad Walkwi"/><PageState loading={!data&&!error} error={error} onRetry={load}/>{data&&<><div className="metrics admin-metrics">{cards.map(({k,l,i:I})=><article key={k}><I/><span>{l}</span><strong>{Number(data[k])||0}</strong></article>)}</div><div className="dashboard-columns"><section className="admin-panel"><h2>Estado de cuentas</h2>{['active','warned','suspended','blocked'].map(x=><div className="count-row" key={x}><Badge value={x}/><strong>{data.accountStatuses?.[x]||0}</strong></div>)}<p className="comparison">Esta semana: <strong>{data.comparison?.thisWeek||0}</strong> <em>{data.comparison?.change>=0?'+':''}{data.comparison?.change||0}%</em></p></section><section className="admin-panel"><h2>Alertas automáticas</h2><div className="alert-row"><AlertTriangle/><span>Usuarios con varias denuncias</span><strong>{data.alerts?.multipleReported||0}</strong></div><div className="alert-row"><Clock3/><span>Suspensiones vencidas</span><strong>{data.alerts?.expiredSuspensions||0}</strong></div><div className="alert-row"><X/><span>Cancelaciones frecuentes</span><strong>{data.alerts?.frequentCancellations||0}</strong></div></section></div><section className="admin-panel recent-panel"><h2>Actividad reciente</h2>{data.recentActivity?.length?data.recentActivity.map(x=><div className="activity-row" key={x._id}><span>{x.action}</span><small>{x.admin?.name||'Administrador'} · {fmt(x.createdAt)}</small></div>):<p>Sin actividad reciente.</p>}</section></>}</>;
}

function UsersPage() {
  const [data,setData]=useState(null),[filters,setFilters]=useState({search:'',role:'',status:'',verified:'',dateFrom:'',hasReports:false,activeBooking:false}),[selected,setSelected]=useState(null),[error,setError]=useState('');
  const load=()=>{setError('');const query=new URLSearchParams(Object.entries(filters).filter(([,v])=>v!==''&&v!==false));api(`/api/admin/users?${query}`).then(setData).catch(e=>setError(e.message))}; useEffect(load,[]);
  const users=Array.isArray(data?.items)?data.items:[];
  const search=filters.search, setSearch=(value)=>setFilters({...filters,search:value});
  const advancedFilters=<div className="filter-panel"><select value={filters.role} onChange={e=>setFilters({...filters,role:e.target.value})}><option value="">Todos los roles</option><option value="user">Dueños</option><option value="walker">Paseadores</option></select><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Todos los estados</option>{['active','warned','suspended','blocked'].map(x=><option key={x} value={x}>{labels[x]}</option>)}</select><select value={filters.verified} onChange={e=>setFilters({...filters,verified:e.target.value})}><option value="">Cualquier verificación</option><option value="true">Verificado</option><option value="false">No verificado</option></select><input type="date" value={filters.dateFrom} onChange={e=>setFilters({...filters,dateFrom:e.target.value})}/><label className="check-label"><input type="checkbox" checked={filters.hasReports} onChange={e=>setFilters({...filters,hasReports:e.target.checked})}/>Con denuncias</label><label className="check-label"><input type="checkbox" checked={filters.activeBooking} onChange={e=>setFilters({...filters,activeBooking:e.target.checked})}/>Con reserva activa</label></div>;
  return <><Header title="Usuarios" subtitle="Consulta perfiles y administra el estado de las cuentas"/><div className="toolbar"><div className="search"><Search/><input placeholder="Buscar por nombre o correo" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()}/></div><button onClick={load}>Buscar</button></div><PageState loading={!data&&!error} error={error} empty={Boolean(data)&&users.length===0} onRetry={load}/>{users.length>0&&<div className="table"><div className="tr th"><span>Usuario</span><span>Rol</span><span>Estado</span><span>Registro</span></div>{users.map(u=><button className="tr" key={u._id} onClick={()=>setSelected(u)}><span><strong>{u.name||'Sin nombre'}</strong><small>{u.email||'Sin correo'}</small></span><span>{labels[u.role]||u.role||'—'}</span><span><Badge value={u.accountStatus||'active'}/></span><span>{fmt(u.createdAt)}</span></button>)}</div>}{selected&&<UserDrawer user={selected} close={()=>setSelected(null)} refresh={load}/>}</>;
}

function UserDrawer({user,close,refresh}) { const [status,setStatus]=useState(user.accountStatus||'active'),[reason,setReason]=useState(''),[busy,setBusy]=useState(false); const save=async()=>{if(!reason.trim())return;setBusy(true);try{await api(`/api/admin/users/${user._id}/status`,{method:'PATCH',body:JSON.stringify({status,reason})});refresh();close()}finally{setBusy(false)}}; return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><aside className="drawer"><button className="close" onClick={close}><X/></button><span className="eyebrow">EXPEDIENTE DE USUARIO</span><h2>{user.name}</h2><p>{user.email}</p><dl><div><dt>Rol</dt><dd>{labels[user.role]}</dd></div><div><dt>Estado actual</dt><dd><Badge value={user.accountStatus||'active'}/></dd></div><div><dt>Verificado</dt><dd>{user.verified?'Sí':'No'}</dd></div></dl><hr/><h3>Cambiar estado de cuenta</h3><label>Nuevo estado<select value={status} onChange={e=>setStatus(e.target.value)}>{['active','warned','suspended','blocked'].map(x=><option value={x} key={x}>{labels[x]}</option>)}</select></label><label>Motivo<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explica la decisión administrativa"/></label><button className="danger" disabled={busy||!reason.trim()} onClick={save}>Guardar decisión</button></aside></div> }

function ReportsPage(){const[data,setData]=useState(null),[selected,setSelected]=useState(null),[error,setError]=useState('');const load=()=>{setError('');api('/api/admin/reports').then(setData).catch(e=>setError(e.message))};useEffect(load,[]);const reports=Array.isArray(data?.items)?data.items:[];return <><Header title="Denuncias" subtitle="Investiga, documenta y resuelve los casos de la comunidad"/><PageState loading={!data&&!error} error={error} empty={Boolean(data)&&reports.length===0} onRetry={load}/>{reports.length>0&&<div className="report-grid">{reports.map(r=><button key={r._id} className="report-card" onClick={()=>setSelected(r)}><div><Badge value={r.priority||'medium'}/><Badge value={r.status||'pending'}/></div><h3>{labels[r.reason]||r.reason?.replaceAll?.('_',' ')||'Denuncia'}</h3><p>{r.description||'Sin descripción.'}</p><footer><span>{r.reporter?.name||'Usuario'}</span><time>{fmt(r.createdAt)}</time></footer></button>)}</div>}{selected&&<ReportDrawer report={selected} close={()=>setSelected(null)} refresh={load}/>}</>}
function ReportDrawer({report,close,refresh}){const[status,setStatus]=useState(report.status),[priority,setPriority]=useState(report.priority||'medium'),[notes,setNotes]=useState(report.adminNotes||'');const save=async()=>{await api(`/api/admin/reports/${report._id}`,{method:'PATCH',body:JSON.stringify({status,priority,adminNotes:notes,assignToMe:true})});refresh();close()};return <div className="overlay"><aside className="drawer"><button className="close" onClick={close}><X/></button><span className="eyebrow">CASO {report._id.slice(-6).toUpperCase()}</span><h2>{labels[report.reason]||report.reason}</h2><p className="description">{report.description}</p><dl><div><dt>Reporta</dt><dd>{report.reporter?.name}</dd></div><div><dt>Reportado</dt><dd>{report.reported?.name}</dd></div><div><dt>Fecha</dt><dd>{fmt(report.createdAt)}</dd></div></dl><label>Prioridad<select value={priority} onChange={e=>setPriority(e.target.value)}>{['low','medium','high','critical'].map(x=><option value={x} key={x}>{labels[x]}</option>)}</select></label><label>Estado<select value={status} onChange={e=>setStatus(e.target.value)}>{['pending','reviewed','dismissed','action_taken'].map(x=><option value={x} key={x}>{labels[x]}</option>)}</select></label><label>Notas internas<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Hallazgos y justificación"/></label><button onClick={save}>Guardar y asignarme el caso</button></aside></div>}

function AuditPage(){const[data,setData]=useState(null),[error,setError]=useState('');const load=()=>{setError('');api('/api/admin/audit').then(setData).catch(e=>setError(e.message))};useEffect(load,[]);const items=Array.isArray(data?.items)?data.items:[];return <><Header title="Auditoría" subtitle="Registro inalterable de decisiones administrativas"/><PageState loading={!data&&!error} error={error} empty={Boolean(data)&&items.length===0} onRetry={load}/>{items.length>0&&<div className="timeline">{items.map(x=><article key={x._id}><span></span><div><strong>{x.action||'Acción administrativa'}</strong><p>{x.admin?.name||'Administrador'} · {x.reason||'Sin observación adicional'}</p><time>{fmt(x.createdAt)}</time></div></article>)}</div>}</>}

function UsersPageV2(){const[data,setData]=useState(null),[filters,setFilters]=useState({search:'',role:'',status:'',verified:'',dateFrom:'',hasReports:false,activeBooking:false}),[selected,setSelected]=useState(null),[error,setError]=useState('');const load=()=>{const q=new URLSearchParams(Object.entries(filters).filter(([,v])=>v!==''&&v!==false));setError('');api(`/api/admin/users?${q}`).then(setData).catch(e=>setError(e.message))};useEffect(load,[]);const items=data?.items||[];return <><Header title="Usuarios" subtitle="Filtros y expedientes administrativos"/><div className="filter-panel"><div className="search"><Search/><input placeholder="Nombre o correo" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/></div><select value={filters.role} onChange={e=>setFilters({...filters,role:e.target.value})}><option value="">Todos los roles</option><option value="user">Dueños</option><option value="walker">Paseadores</option></select><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Todos los estados</option>{['active','warned','suspended','blocked'].map(x=><option value={x} key={x}>{labels[x]}</option>)}</select><select value={filters.verified} onChange={e=>setFilters({...filters,verified:e.target.value})}><option value="">Verificación</option><option value="true">Verificado</option><option value="false">Pendiente</option></select><input type="date" value={filters.dateFrom} onChange={e=>setFilters({...filters,dateFrom:e.target.value})}/><label className="check-label"><input type="checkbox" checked={filters.hasReports} onChange={e=>setFilters({...filters,hasReports:e.target.checked})}/>Con denuncias</label><label className="check-label"><input type="checkbox" checked={filters.activeBooking} onChange={e=>setFilters({...filters,activeBooking:e.target.checked})}/>Reserva activa</label><button onClick={load}>Aplicar filtros</button></div><PageState loading={!data&&!error} error={error} empty={data&&items.length===0} onRetry={load}/>{items.length>0&&<div className="table"><div className="tr th"><span>Usuario</span><span>Rol</span><span>Estado</span><span>Registro</span></div>{items.map(u=><button className="tr" key={u._id} onClick={()=>setSelected(u)}><span><strong>{u.name}</strong><small>{u.email}</small></span><span>{labels[u.role]||u.role}</span><span><Badge value={u.accountStatus||'active'}/></span><span>{fmt(u.createdAt)}</span></button>)}</div>}{selected&&<UserDrawer user={selected} close={()=>setSelected(null)} refresh={load}/>}</>}

function AccountDrawer({user,close,refresh}){
  const [status,setStatus]=useState(user.accountStatus||'active'),[reason,setReason]=useState(''),[until,setUntil]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const save=async()=>{if(!reason.trim())return;if(!window.confirm(`¿Confirmas cambiar el estado de ${user.name} a ${labels[status]}?`))return;setBusy(true);setError('');try{await api(`/api/admin/users/${user._id}/status`,{method:'PATCH',body:JSON.stringify({status,reason,until:status==='suspended'&&until?until:null})});refresh();close()}catch(err){setError(err.message)}finally{setBusy(false)}};
  return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><aside className="drawer"><button className="close" onClick={close}><X/></button><span className="eyebrow">EXPEDIENTE DE USUARIO</span><h2>{user.name}</h2><p>{user.email}</p><dl><div><dt>Rol</dt><dd>{labels[user.role]}</dd></div><div><dt>Estado actual</dt><dd><Badge value={user.accountStatus||'active'}/></dd></div><div><dt>Verificado</dt><dd>{user.verified?'Sí':'No'}</dd></div></dl><hr/><h3>Gestionar estado de cuenta</h3><label>Nuevo estado<select value={status} onChange={e=>setStatus(e.target.value)}>{['active','warned','suspended','blocked'].map(x=><option value={x} key={x}>{labels[x]}</option>)}</select></label>{status==='suspended'&&<label>Suspender hasta<input type="date" min={new Date().toISOString().slice(0,10)} value={until} onChange={e=>setUntil(e.target.value)}/></label>}<label>Motivo<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motivo obligatorio"/></label>{error&&<div className="error">{error}</div>}<button className={status==='active'?'':'danger'} disabled={busy||!reason.trim()} onClick={save}>{busy?'Guardando…':status==='active'?'Reactivar cuenta':`Confirmar: ${labels[status]}`}</button></aside></div>;
}

function UsersPageV3(){
  const UserDrawer=AccountDrawer;
  const [data,setData]=useState(null),[filters,setFilters]=useState({search:'',role:'',status:'',verified:'',dateFrom:'',hasReports:false,activeBooking:false}),[showFilters,setShowFilters]=useState(false),[selected,setSelected]=useState(null),[error,setError]=useState('');
  const load=()=>{const q=new URLSearchParams(Object.entries(filters).filter(([,v])=>v!==''&&v!==false));setError('');api(`/api/admin/users?${q}`).then(setData).catch(e=>setError(e.message))};
  useEffect(load,[]); const items=data?.items||[];
  const clearFilters=()=>setFilters(current=>({...current,role:'',status:'',verified:'',dateFrom:'',hasReports:false,activeBooking:false}));
  return <><Header title="Usuarios" subtitle="Busca cuentas y consulta sus expedientes"/><section className="user-search-box"><div className="large-search"><Search/><input placeholder="Buscar usuario por nombre o correo" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})} onKeyDown={e=>e.key==='Enter'&&load()}/><button onClick={load}>Buscar</button></div><button className={`filter-toggle ${showFilters?'open':''}`} onClick={()=>setShowFilters(!showFilters)}><span>Filtros avanzados</span><em>{showFilters?'Ocultar':'Mostrar'}</em></button>{showFilters&&<div className="advanced-filter-content"><select value={filters.role} onChange={e=>setFilters({...filters,role:e.target.value})}><option value="">Todos los roles</option><option value="user">Dueños</option><option value="walker">Paseadores</option></select><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Todos los estados</option>{['active','warned','suspended','blocked'].map(x=><option value={x} key={x}>{labels[x]}</option>)}</select><select value={filters.verified} onChange={e=>setFilters({...filters,verified:e.target.value})}><option value="">Cualquier verificación</option><option value="true">Verificado</option><option value="false">Pendiente</option></select><label>Registrado desde<input type="date" value={filters.dateFrom} onChange={e=>setFilters({...filters,dateFrom:e.target.value})}/></label><label className="check-label"><input type="checkbox" checked={filters.hasReports} onChange={e=>setFilters({...filters,hasReports:e.target.checked})}/>Con denuncias recibidas</label><label className="check-label"><input type="checkbox" checked={filters.activeBooking} onChange={e=>setFilters({...filters,activeBooking:e.target.checked})}/>Con reserva activa</label><div className="filter-actions"><button className="secondary-button" onClick={clearFilters}>Limpiar</button><button onClick={load}>Aplicar filtros</button></div></div>}</section><PageState loading={!data&&!error} error={error} empty={data&&items.length===0} onRetry={load}/>{items.length>0&&<><p className="result-count">{data.total} usuarios encontrados</p><div className="table"><div className="tr th"><span>Usuario</span><span>Rol</span><span>Estado</span><span>Registro</span></div>{items.map(u=><button className="tr" key={u._id} onClick={()=>setSelected(u)}><span><strong>{u.name}</strong><small>{u.email}</small></span><span>{labels[u.role]||u.role}</span><span><Badge value={u.accountStatus||'active'}/></span><span>{fmt(u.createdAt)}</span></button>)}</div></>}{selected&&<UserDrawer user={selected} close={()=>setSelected(null)} refresh={load}/>}</>;
}

function ReviewsAdmin(){const[data,setData]=useState(null),[error,setError]=useState('');const load=()=>api('/api/admin/reviews').then(setData).catch(e=>setError(e.message));useEffect(load,[]);const remove=async(item)=>{if(!window.confirm('¿Eliminar esta reseña y recalcular la calificación?'))return;await api(`/api/admin/reviews/${item._id}`,{method:'DELETE',body:JSON.stringify({reason:'Moderación administrativa'})});load()};return <><Header title="Reseñas" subtitle="Calificaciones publicadas por los usuarios"/><PageState loading={!data&&!error} error={error} empty={data&&data.items.length===0} onRetry={load}/><div className="review-admin-grid">{data?.items?.map(item=><article className="admin-panel" key={item._id}><div className="review-stars">{'★'.repeat(item.rating)}{'☆'.repeat(5-item.rating)}</div><p>{item.comment}</p><dl><div><dt>Publicada por</dt><dd>{item.reviewer?.name} · {item.reviewer?.email}</dd></div><div><dt>Dirigida a</dt><dd>{item.reviewed?.name} · {item.reviewed?.email}</dd></div><div><dt>Servicio</dt><dd>{item.booking?.petName||'Reserva'} · {fmt(item.booking?.startTime)}</dd></div></dl><button className="delete-review" onClick={()=>remove(item)}><Trash2/>Eliminar reseña</button></article>)}</div></>}

const bookingStatus = { pending:'Pendiente', accepted:'Aceptada', in_progress:'En progreso', completed:'Completada', cancelled:'Cancelada' };
function BookingCards({ items, role }) {
  if (!items?.length) return <PageState empty/>;
  return <div className="portal-grid">{items.map(item => { const person=role==='walker'?item.client:item.walker; return <article className="portal-card" key={item._id}><div className="card-top"><Badge value={item.status}/><time>{fmt(item.startTime)}</time></div><h3>{item.petName||'Servicio Walkwi'}</h3><p>{role==='walker'?'Dueño':'Paseador'}: <strong>{person?.name||'Sin asignar'}</strong></p><dl><div><dt>Duración</dt><dd>{item.duration||0} min</dd></div><div><dt>Precio</dt><dd>${Number(item.price||0).toFixed(2)}</dd></div><div><dt>Estado</dt><dd>{bookingStatus[item.status]||item.status}</dd></div></dl></article>})}</div>;
}

function ProfileEditor({ user, onSaved }) {
  const [editing,setEditing]=useState(false),[form,setForm]=useState({name:user.name||'',email:user.email||'',phone:user.phone||''}),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>setForm({name:user.name||'',email:user.email||'',phone:user.phone||''}),[user]);
  const save=async(event)=>{event.preventDefault();setBusy(true);setError('');setMessage('');try{const result=await api('/api/admin/portal/profile',{method:'PATCH',body:JSON.stringify(form)});onSaved(result.user);setMessage(result.message);setEditing(false)}catch(err){setError(err.message)}finally{setBusy(false)}};
  if(!editing)return <div className="profile-edit-actions">{message&&<span className="success-message">{message}</span>}<button onClick={()=>setEditing(true)}><Pencil/>Editar perfil</button></div>;
  return <form className="profile-edit-form" onSubmit={save}><h3>Editar información básica</h3><div className="form-grid"><label>Nombre<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Correo<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Teléfono<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label></div>{error&&<div className="error">{error}</div>}<div className="form-actions"><button type="button" className="secondary-button" onClick={()=>{setEditing(false);setError('')}}>Cancelar</button><button disabled={busy}>{busy?'Guardando…':'Guardar cambios'}</button></div></form>;
}

function PetCard({ pet, onSaved }) {
  const [editing,setEditing]=useState(false),[form,setForm]=useState({name:pet.name||'',breed:pet.breed||'',age:pet.age||'',weight:pet.weight||'',insured:Boolean(pet.insured),careNotes:pet.careNotes||''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const save=async(event)=>{event.preventDefault();setBusy(true);setError('');try{const result=await api(`/api/admin/portal/pets/${pet._id}`,{method:'PATCH',body:JSON.stringify(form)});onSaved(result.pet);setEditing(false)}catch(err){setError(err.message)}finally{setBusy(false)}};
  return <article className="portal-card pet-card-web"><div className="pet-photo"><PawPrint/><img src={pet.photoUri||''} alt={`Foto de ${pet.name||'mascota'}`} onError={(event)=>{event.currentTarget.style.display='none'}}/></div>{editing?<form className="pet-edit-form" onSubmit={save}><h3>Editar mascota</h3><div className="pet-form-grid"><label>Nombre<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Raza<input value={form.breed} onChange={e=>setForm({...form,breed:e.target.value})} required/></label><label>Edad<input value={form.age} onChange={e=>setForm({...form,age:e.target.value})} required/></label><label>Peso<input value={form.weight} onChange={e=>setForm({...form,weight:e.target.value})} required/></label></div><label className="check-label"><input type="checkbox" checked={form.insured} onChange={e=>setForm({...form,insured:e.target.checked})}/>Cuenta con seguro</label><label>Notas de cuidado<textarea value={form.careNotes} onChange={e=>setForm({...form,careNotes:e.target.value})}/></label>{error&&<div className="error">{error}</div>}<div className="form-actions"><button type="button" className="secondary-button" onClick={()=>{setEditing(false);setError('')}}>Cancelar</button><button disabled={busy}>{busy?'Guardando…':'Guardar'}</button></div></form>:<><div className="pet-card-title"><div><h3>{pet.name||'Mascota'}</h3><p>{pet.breed||'Raza no registrada'}</p></div><button onClick={()=>setEditing(true)} aria-label={`Editar ${pet.name||'mascota'}`}><Pencil/></button></div><dl><div><dt>Edad</dt><dd>{pet.age||'—'}</dd></div><div><dt>Peso</dt><dd>{pet.weight||'—'}</dd></div><div><dt>Seguro</dt><dd>{pet.insured?'Sí':'No'}</dd></div></dl>{pet.careNotes&&<p>{pet.careNotes}</p>}</>}</article>;
}

function PortalPage({ section, role }) {
  const [data,setData]=useState(null),[error,setError]=useState('');
  const load=()=>{setError('');api('/api/admin/portal/overview').then(setData).catch(e=>setError(e.message))};
  useEffect(load,[]);
  if (!data || error) return <><Header title="Portal Walkwi" subtitle="Tu información en un solo lugar"/><PageState loading={!data&&!error} error={error} onRetry={load}/></>;
  const {user,bookings,reports=[],notifications=[]}=data;
  const titles={summary:'Mi resumen',profile:'Mi perfil',pets:'Mis mascotas',active:role==='walker'?'Servicios activos':'Reservas activas',upcoming:role==='walker'?'Próximos servicios':'Próximas reservas',history:'Historial de servicios',myreports:'Denuncias',account:'Estado de mi cuenta',notifications:'Notificaciones administrativas',verification:'Estado de verificación',availability:'Disponibilidad',reviews:'Calificaciones y reseñas'};
  const title=titles[section]||'Mi resumen';
  let content;
  if(section==='summary') content=<><div className="metrics portal-metrics"><article><Clock3/><span>Servicios activos</span><strong>{bookings.active.length}</strong></article><article><CalendarClock/><span>Próximos</span><strong>{bookings.upcoming.length}</strong></article><article><History/><span>Completados</span><strong>{bookings.history.filter(x=>x.status==='completed').length}</strong></article><article><Bell/><span>Notificaciones</span><strong>{notifications.length}</strong></article></div><section className="welcome-card"><div><span className="eyebrow">BIENVENIDO A WALKWI</span><h2>{user.name}</h2><p>Aquí puedes consultar tu actividad. Las operaciones de servicios se realizan desde la app móvil.</p></div><img src="/walkwi-logo.png" alt="Walkwi"/></section></>;
  else if(section==='profile') content=<section className="profile-card"><div className="profile-avatar">{user.profilePhotoUri?<img src={user.profilePhotoUri} alt="Foto de perfil"/>:(user.name?.[0]||'U')}</div><div className="profile-details"><div className="profile-title-row"><div><h2>{user.name}</h2><p>{user.email}</p></div></div><dl><div><dt>Teléfono</dt><dd>{user.phone||'No registrado'}</dd></div><div><dt>Ubicación</dt><dd>{user.location||'No registrada'}</dd></div>{role==='walker'&&<><div><dt>Experiencia</dt><dd>{user.experience||'No registrada'}</dd></div><div><dt>Precio por hora</dt><dd>${Number(user.pricePerHour||0).toFixed(2)}</dd></div></>}</dl><div className="profile-account-box"><div><ShieldCheck/><span>Estado de cuenta</span></div><Badge value={user.accountStatus||'active'}/><p>{user.sanction?.reason||'Tu cuenta no tiene medidas administrativas activas.'}</p></div><ProfileEditor user={user} onSaved={(updated)=>setData(current=>({...current,user:updated}))}/></div></section>;
  else if(section==='pets') content=user.pets?.length?<div className="portal-grid">{user.pets.map((pet,i)=><PetCard key={pet._id||i} pet={pet} onSaved={(updated)=>setData(current=>({...current,user:{...current.user,pets:current.user.pets.map(item=>item._id===updated._id?updated:item)}}))}/>)}</div>:<PageState empty/>;
  else if(['active','upcoming','history'].includes(section)) content=<BookingCards items={bookings[section]} role={role}/>;
  else if(section==='myreports') content=reports.length?<div className="portal-grid">{reports.map(r=><article className="portal-card" key={r._id}><div className="card-top"><Badge value={r.status||'pending'}/><time>{fmt(r.createdAt)}</time></div><h3>{labels[r.reason]||r.reason?.replaceAll?.('_',' ')||'Denuncia'}</h3><p>{r.description}</p>{r.adminNotes&&<aside>Respuesta: {r.adminNotes}</aside>}</article>)}</div>:<PageState empty/>;
  else if(section==='account') content=<section className="status-panel"><ShieldCheck/><h2><Badge value={user.accountStatus||'active'}/></h2><p>{user.sanction?.reason||'Tu cuenta no tiene medidas administrativas activas.'}</p>{user.sanction?.until&&<small>Hasta: {fmt(user.sanction.until)}</small>}</section>;
  else if(section==='notifications') content=notifications.length?<div className="notification-list">{notifications.map((n,i)=><article key={i}><Bell/><div><strong>{n.title}</strong><p>{n.message}</p><time>{fmt(n.createdAt)}</time></div></article>)}</div>:<PageState empty/>;
  else if(section==='verification') content=<section className="status-panel"><ShieldCheck/><h2>{user.verified?'Perfil verificado':'Verificación pendiente'}</h2><p>{user.verified?'Tu perfil profesional fue validado por Walkwi.':'El equipo administrativo todavía está revisando tu perfil.'}</p></section>;
  else if(section==='availability') content=<section className="profile-card"><CalendarClock size={46}/><div><h2>Disponibilidad registrada</h2><p>{user.availableDays?.length?user.availableDays.join(', '):'No hay días registrados.'}</p><dl><div><dt>Desde</dt><dd>{user.availableHours?.start||'—'}</dd></div><div><dt>Hasta</dt><dd>{user.availableHours?.end||'—'}</dd></div></dl></div></section>;
  else if(section==='reviews') content=<><div className="rating-card"><Star/><strong>{Number(user.rating||0).toFixed(1)}</strong><span>{user.reviewCount||0} reseñas registradas</span></div><PageState empty={!(user.reviewCount>0)}/></>;
  return <><Header title={title} subtitle={role==='walker'?'Portal informativo del paseador':'Portal informativo del dueño'}/>{content}</>;
}
function Header({title,subtitle}){return <header className="page-header"><div><h1>{title}</h1><p>{subtitle}</p></div><span className="live"><i/> Sistema conectado</span></header>}
function Badge({value}){return <em className={`badge b-${value}`}>{labels[value]||value}</em>}

function SidebarNavigation({ items, active, onSelect }) {
  let previousGroup='';
  return <nav className="sidebar-nav" aria-label="Navegación principal">{items.map(({id,label,icon:Icon,group})=>{const showGroup=group!==previousGroup;previousGroup=group;return <React.Fragment key={id}>{showGroup&&<span className="nav-group">{group}</span>}<button title={label} className={active===id?'active':''} onClick={()=>onSelect(id)}><Icon/><span>{label}</span></button></React.Fragment>})}</nav>;
}

export default function App(){
  const[user,setUser]=useState(null),[tab,setTab]=useState('dashboard'),[checking,setChecking]=useState(Boolean(session.token)),[collapsed,setCollapsed]=useState(()=>localStorage.getItem('walkwi_menu_collapsed')==='true');
  useEffect(()=>{if(session.token)api('/api/admin/auth/me').then(d=>{setUser(d.user);setTab(d.user.role==='admin'?'dashboard':'summary')}).catch(()=>session.set(null)).finally(()=>setChecking(false))},[]);
  if(checking)return <div className="loading">Cargando Walkwi…</div>;
  if(!user)return <Login onLogin={(next)=>{setUser(next);setTab(next.role==='admin'?'dashboard':'summary')}}/>;
  const nav=roleNav[user.role]||roleNav.user;
  const AdminPage={dashboard:Dashboard,users:UsersPageV3,reports:ReportsPage,reviews:ReviewsAdmin,audit:AuditPage}[tab]||Dashboard;
  const toggleMenu=()=>setCollapsed(value=>{localStorage.setItem('walkwi_menu_collapsed',String(!value));return !value});
  return <div className={`shell ${collapsed?'menu-collapsed':''}`}><aside className="sidebar"><header className="sidebar-head"><div className="logo"><img src="/walkwi-logo.png" alt="Walkwi"/><div><strong>Walkwi</strong><span>{user.role==='admin'?'Administración':user.role==='walker'?'Paseador':'Mi cuenta'}</span></div></div><button className="menu-toggle" onClick={toggleMenu} aria-label={collapsed?'Expandir menú':'Contraer menú'} title={collapsed?'Expandir menú':'Contraer menú'}><Menu/></button></header><SidebarNavigation items={nav} active={tab} onSelect={setTab}/><footer className="sidebar-footer"><div className="admin"><span>{user.name?.[0]||'U'}</span><div><strong>{user.name||'Usuario'}</strong><small>{labels[user.role]||user.role}</small></div></div><button className="logout" onClick={()=>{session.set(null);setUser(null)}}><LogOut/><span>Cerrar sesión</span></button></footer></aside><main className="content"><ErrorBoundary screen={tab}>{user.role==='admin'?<AdminPage/>:<PortalPage section={tab} role={user.role}/>}</ErrorBoundary></main></div>
}
